### ISSUE TITLE
[Crash] - Mushroom Stew?

### ISSUE THREAD

**Issue by wolfkidsounds** [wolfkidsounds/Universe-Modpack#213]
User: Firnunir|Patrick
[crash-2021-03-16_14.27.55-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6151591/crash-2021-03-16_14.27.55-client.txt)

[crash-2021-03-16_14.28.41-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6151592/crash-2021-03-16_14.28.41-client.txt)

**Comment by wolfkidsounds** [comment]
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:rabbit_stew_from_red_mushroom (net.minecraft.item.crafting.ShapedRecipes@483f19c0) produces unregistered item minecraft:rabbit_stew (net.minecraft.item.ItemSoup@318353)
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Recipe minecraft:rabbit_stew_from_red_mushroom (net.minecraft.item.crafting.ShapedRecipes@483f19c0) produces unregistered item minecraft:rabbit_stew (net.minecraft.item.ItemSoup@318353)
    at net.minecraftforge.registries.GameData$RecipeCallbacks.onValidate(GameData.java:462)
    at net.minecraftforge.registries.GameData$RecipeCallbacks.onValidate(GameData.java:450)
    at net.minecraftforge.registries.ForgeRegistry.validateContent(ForgeRegistry.java:474)
    at net.minecraftforge.registries.GameData.lambda$injectSnapshot$7(GameData.java:607)
    at net.minecraftforge.registries.GameData$$Lambda$4491/429541890.accept(Unknown Source)
    at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:528)
    at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:607)
    at net.minecraftforge.fml.common.network.handshake.FMLHandshakeClientState$4.lambda$accept$0(FMLHandshakeClientState.java:159)
    at net.minecraftforge.fml.common.network.handshake.FMLHandshakeClientState$4$$Lambda$4490/1230939315.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more
    ```

**Comment by stkl-tea** [comment]
falls ja, wollen wir dann den mushroom stew rausnehmen statt fixen?
ist jz nicht gerade das coolste item, zumal wir viel anderes futter haben ^^

**Comment by wolfkidsounds** [comment]
Frage hier ist, was genau das problem war. - Ich konnte jetzt nur deuten, das der client handshake (also die abstimmung mit dem server) ein anderes rezept für "mushroom stew" ergeben hat.

-> Wir können auf jeden fall das rezept problem lösen, indem wir es einfach entfernen und mit crafttweaker festsetzen. Damit solle sich das bereits lösen. - Warum der fehler auftritt kann ich dem crash leider nicht genau entnehmen :/
