### ISSUE TITLE
[Crash] - HungerTweaker, CraftTweaker

### ISSUE THREAD

**Issue by wolfkidsounds** [wolfkidsounds/Universe-Modpack#221]
```
java.lang.NullPointerException
    at coolsquid.hungertweaker.ModEventHandler.on(ModEventHandler.java:51)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1771_ModEventHandler_on_GetFoodValues.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getFoodValues(AppleCoreAccessorMutatorImpl.java:109)
    at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getFoodValuesForPlayer(AppleCoreAccessorMutatorImpl.java:118)
    at squeek.appleskin.helpers.AppleCoreHelper.getModifiedFoodValues(AppleCoreHelper.java:24)
    at squeek.appleskin.helpers.FoodHelper.getModifiedFoodValues(FoodHelper.java:69)
    at squeek.appleskin.client.HUDOverlayHandler.onRender(HUDOverlayHandler.java:104)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2209_HUDOverlayHandler_onRender_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
    at net.minecraftforge.client.GuiIngameForge.renderFood(GuiIngameForge.java:535)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:156)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    ```

**Comment by wolfkidsounds** [comment]
Maybe related to #220
